import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import identifiers from '../app.identifiers.js';

const bundleId = `${identifiers.isDevVariant() ? identifiers.DEV_BUNDLE_IDENTIFIER : identifiers.IOS_PROD_BUNDLE_IDENTIFIER}.watchkitapp`;
const buildDirectory = mkdtempSync(join(tmpdir(), 'xot-watch-'));

console.log('› Building XoTWatch and its companion widget...');
// Build the Watch target directly. The autogenerated scheme also builds the
// phone and ExpoWidgetsTarget, which requires the phone's installed Pods.
execFileSync(
  'xcodebuild',
  [
    '-project',
    'ios/XonTrack.xcodeproj',
    '-target',
    'XoTWatch',
    '-configuration',
    'Debug',
    '-sdk',
    'watchsimulator',
    'CODE_SIGNING_ALLOWED=NO',
    `SYMROOT=${buildDirectory}`,
    'build',
    '-quiet',
  ],
  { stdio: 'inherit' }
);

const builtAppPath = join(buildDirectory, 'Debug-watchsimulator/XoTWatch.app');
if (!existsSync(builtAppPath)) {
  throw new Error(`Could not find the built Watch app at ${builtAppPath}`);
}

console.log('› Finding an available Apple Watch simulator...');
const { devices } = JSON.parse(
  execFileSync('xcrun', ['simctl', 'list', 'devices', 'available', '-j'], {
    encoding: 'utf8',
  })
);
const watches = Object.entries(devices)
  .filter(([runtime]) => runtime.includes('watchOS'))
  .flatMap(([, list]) => list);
const watchDevice =
  watches.find((device) => device.state === 'Booted') ||
  watches.find((device) =>
    device.name.includes('Apple Watch Series 11 (46mm)')
  ) ||
  watches[0];
if (!watchDevice) throw new Error('No available watchOS simulator found.');

execFileSync('open', ['-a', 'Simulator'], { stdio: 'ignore' });
if (watchDevice.state !== 'Booted') {
  execFileSync('xcrun', ['simctl', 'boot', watchDevice.udid], {
    stdio: 'inherit',
  });
}
execFileSync('xcrun', ['simctl', 'bootstatus', watchDevice.udid, '-b'], {
  stdio: 'inherit',
});
execFileSync('xcrun', ['simctl', 'install', watchDevice.udid, builtAppPath], {
  stdio: 'inherit',
});
execFileSync('xcrun', ['simctl', 'launch', watchDevice.udid, bundleId], {
  stdio: 'inherit',
});
console.log('✔ X on Track opened on the Watch simulator.');
