// Renders the Progress X geometry for the watch complication as Swift.
//
// The watch widget is its own compiled Swift module and cannot read
// @workspace/shared, so the X it draws is generated from the same geometry
// JSON the phone and web use, together with the per-segment path lengths the
// shared reveal splits progress across. Kept free of `import.meta` so Jest's
// CommonJS transform can import it; the CLI lives in
// generate-watch-progress-x.mjs.
import {
  progressionXGeometry,
  progressionXSegmentLengths,
} from '../../shared/src/brand/progressionX.ts';

const round = (value) => Number(value.toFixed(3));

function hexColor(hex) {
  const value = hex.replace('#', '');
  const channel = (offset) =>
    round(parseInt(value.slice(offset, offset + 2), 16) / 255);
  return `Color(red: ${channel(0)}, green: ${channel(2)}, blue: ${channel(4)})`;
}

function point(x, y) {
  return `CGPoint(x: ${x}, y: ${y})`;
}

function segmentSource(segment, index) {
  const { gradient } = segment;
  const lines = [
    `        ProgressXSegment(`,
    `            id: "${segment.id}",`,
    `            isStroke: ${segment.kind === 'stroke'},`,
    `            path: "${segment.path}",`,
    `            taperPath: ${segment.taperPath ? `"${segment.taperPath}"` : 'nil'},`,
    `            guide: "${segment.guide}",`,
    `            strokeWidth: ${segment.strokeWidth},`,
    `            revealWidth: ${segment.revealWidth},`,
    `            roundCap: ${segment.linecap !== 'butt'},`,
    `            length: ${round(progressionXSegmentLengths[index])},`,
    `            gradientStart: ${point(gradient.x1, gradient.y1)},`,
    `            gradientEnd: ${point(gradient.x2, gradient.y2)},`,
    `            from: ${hexColor(gradient.from)},`,
    `            to: ${hexColor(gradient.to)}`,
    `        ),`,
  ];
  return lines.join('\n');
}

export function renderWatchProgressXGeometry() {
  const [, , width, height] = progressionXGeometry.viewBox
    .split(' ')
    .map(Number);
  return `// Generated by scripts/generate-watch-progress-x.mjs from
// shared/src/brand/progressionX.geometry.json. Do not edit by hand; run
// \`node scripts/generate-watch-progress-x.mjs\` after changing the geometry.

import SwiftUI

struct ProgressXSegment {
    let id: String
    let isStroke: Bool
    let path: String
    let taperPath: String?
    let guide: String
    let strokeWidth: CGFloat
    let revealWidth: CGFloat
    let roundCap: Bool
    /// Length of \`guide\`, measured the same way as the shared reveal.
    let length: Double
    let gradientStart: CGPoint
    let gradientEnd: CGPoint
    let from: Color
    let to: Color
}

enum ProgressXGeometry {
    static let size = CGSize(width: ${width}, height: ${height})
    static let baselineDark = ${hexColor(progressionXGeometry.baselineDark)}
    static let segments: [ProgressXSegment] = [
${progressionXGeometry.segments.map(segmentSource).join('\n')}
    ]
}
`;
}
