/** Pinned BLS 4.0 workbook headers. Source: https://www.blsdb.de/download.
 * SHA-256: 12b7a6ba62807ec9b301eb276f897dc85f99b2292311618dec3749a12d984c91
 * Values are per 100 g. Blocked forms must never enter alias matching.
 */
export const BLS_COMPONENT_MANIFEST = [
  {
    code: "ENERCJ",
    label: "ENERCJ Energie (Kilojoule) [kJ/100g]",
    unit: "kJ",
    status: "out_of_scope",
  },
  {
    code: "ENERCC",
    label: "ENERCC Energie (Kilokalorien) [kcal/100g]",
    unit: "kcal",
    status: "out_of_scope",
  },
  {
    code: "WATER",
    label: "WATER Wasser [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "PROT625",
    label: "PROT625 Protein (Nx6,25) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FAT",
    label: "FAT Fett [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "CHO",
    label: "CHO Kohlenhydrate, verfügbar [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBT",
    label: "FIBT Ballaststoffe, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "ALC",
    label: "ALC Alkohol (Ethanol) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "OA",
    label: "OA Organische Säuren, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "ASH",
    label: "ASH Rohasche [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "VITA",
    label: "VITA Vitamin A, Retinol-Äquivalent (RE) [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Vitamin A errata",
  },
  {
    code: "VITAA",
    label: "VITAA Vitamin A, Retinol-Aktivitäts-Äquivalent (RAE) [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Vitamin A errata",
  },
  {
    code: "RETOL",
    label: "RETOL Retinol [µg/100g]",
    unit: "µg",
    status: "out_of_scope",
  },
  {
    code: "CARTB",
    label: "CARTB Beta‑Carotin [µg/100g]",
    unit: "µg",
    status: "out_of_scope",
  },
  {
    code: "CAROTPAXB",
    label: "CAROTPAXB Carotinoide, außer Beta-Carotin [µg/100g]",
    unit: "µg",
    status: "out_of_scope",
  },
  {
    code: "VITD",
    label: "VITD Vitamin D [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "vitamin_d",
  },
  {
    code: "CHOCAL",
    label: "CHOCAL Vitamin D3 (Cholecalciferol) [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "ERGCAL",
    label: "ERGCAL Vitamin D2 (Ergocalciferol) [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "VITE",
    label: "VITE Vitamin E (Alpha-Tocopherol) [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "vitamin_e",
  },
  {
    code: "TOCPHA",
    label: "TOCPHA Alpha‑Tocopherol [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "TOCPHB",
    label: "TOCPHB Beta-Tocopherol [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "TOCPHG",
    label: "TOCPHG Gamma-Tocopherol [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "TOCPHD",
    label: "TOCPHD Delta-Tocopherol [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "TOCTRA",
    label: "TOCTRA Alpha-Tocotrienol [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "VITK",
    label: "VITK Vitamin K [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "vitamin_k",
  },
  {
    code: "VITK1",
    label: "VITK1 Vitamin K1 (Phyllochinon) [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "VITK2",
    label: "VITK2 Vitamin K2 (Menachinone) [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "THIA",
    label: "THIA Vitamin B1 (Thiamin) [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "thiamin",
  },
  {
    code: "RIBF",
    label: "RIBF Vitamin B2 (Riboflavin) [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "riboflavin",
  },
  {
    code: "NIAEQ",
    label: "NIAEQ Niacin-Äquivalent [mg/100g]",
    unit: "mg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "NIA",
    label: "NIA Niacin [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "niacin",
  },
  {
    code: "PANTAC",
    label: "PANTAC Pantothensäure [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "pantothenic_acid",
  },
  {
    code: "VITB6",
    label: "VITB6 Vitamin B6 [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "vitamin_b6",
  },
  {
    code: "BIOT",
    label: "BIOT Biotin [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "biotin",
  },
  {
    code: "FOL",
    label: "FOL Folat-Äquivalent [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "FOLFD",
    label: "FOLFD Folat [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "FOLAC",
    label: "FOLAC Folsäure, synthetisch [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "VITB12",
    label: "VITB12 Vitamin B12 (Cobalamine) [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "vitamin_b12",
  },
  {
    code: "VITC",
    label: "VITC Vitamin C [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "vitamin_c",
  },
  {
    code: "NACL",
    label: "NACL Salz (Natriumchlorid) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "NA",
    label: "NA Natrium [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "sodium",
  },
  {
    code: "CLD",
    label: "CLD Chlorid [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "chloride",
  },
  {
    code: "K",
    label: "K Kalium [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "potassium",
  },
  {
    code: "CA",
    label: "CA Calcium [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "calcium",
  },
  {
    code: "MG",
    label: "MG Magnesium [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "magnesium",
  },
  {
    code: "P",
    label: "P Phosphor [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "phosphorus",
  },
  {
    code: "S",
    label: "S Schwefel [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "FE",
    label: "FE Eisen [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "iron",
  },
  {
    code: "ZN",
    label: "ZN Zink [mg/100g]",
    unit: "mg",
    status: "supported",
    catalogId: "zinc",
  },
  {
    code: "ID",
    label: "ID Iodid [µg/100g]",
    unit: "µg",
    status: "blocked",
    reason: "Source form is not interchangeable with the canonical total",
  },
  {
    code: "CU",
    label: "CU Kupfer [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "copper",
  },
  {
    code: "MN",
    label: "MN Mangan [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "manganese",
  },
  {
    code: "FD",
    label: "FD Fluorid [µg/100g]",
    unit: "µg",
    status: "out_of_scope",
  },
  {
    code: "CR",
    label: "CR Chrom [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "chromium",
  },
  {
    code: "MO",
    label: "MO Molybdän [µg/100g]",
    unit: "µg",
    status: "supported",
    catalogId: "molybdenum",
  },
  {
    code: "ACEAC",
    label: "ACEAC Essigsäure [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "CITAC",
    label: "CITAC Zitronensäure [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "LACAC",
    label: "LACAC Milchsäure [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "MALAC",
    label: "MALAC Äpfelsäure [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "TARAC",
    label: "TARAC Weinsäure [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "POLYL",
    label: "POLYL Zuckeralkohole, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "MANTL",
    label: "MANTL Mannit [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "SORTL",
    label: "SORTL Sorbit [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "XYLTL",
    label: "XYLTL Xylit [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "MNSAC",
    label: "MNSAC Monosaccharide, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "GLUS",
    label: "GLUS Glucose [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FRUS",
    label: "FRUS Fructose [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "GALS",
    label: "GALS Galactose [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "DISAC",
    label: "DISAC Disaccharide, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "SUCS",
    label: "SUCS Saccharose [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "MALS",
    label: "MALS Maltose [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "LACS",
    label: "LACS Lactose [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "SUGAR",
    label: "SUGAR Zucker (Mono- und Disaccharide), gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "OLSAC",
    label: "OLSAC Oligosaccharide, verfügbar [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "STARCH",
    label: "STARCH Stärke (Stärke, Glykogen, Dextrine) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBLMW",
    label: "FIBLMW Ballaststoffe, niedermolekular [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBHMW",
    label: "FIBHMW Ballaststoffe, hochmolekular [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBINS",
    label: "FIBINS Ballaststoffe, wasserunlöslich [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBSOL",
    label: "FIBSOL Ballaststoffe, wasserlöslich [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBHMWS",
    label: "FIBHMWS Ballaststoffe, hochmolekular, wasserlöslich [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FIBHMWI",
    label: "FIBHMWI Ballaststoffe, hochmolekular, wasserunlöslich [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FASAT",
    label: "FASAT Fettsäuren, gesättigt, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F4:0",
    label: "F4:0 Fettsäure C4:0 (Buttersäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F6:0",
    label: "F6:0 Fettsäure C6:0 (Capronsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F8:0",
    label: "F8:0 Fettsäure C8:0 (Caprylsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F10:0",
    label: "F10:0 Fettsäure C10:0 (Caprinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F12:0",
    label: "F12:0 Fettsäure C12:0 (Laurinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F14:0",
    label: "F14:0 Fettsäure C14:0 (Myristinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F15:0",
    label: "F15:0 Fettsäure C15:0 (Pentadecylsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F16:0",
    label: "F16:0 Fettsäure C16:0 (Palmitinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F17:0",
    label: "F17:0 Fettsäure C17:0 (Margarinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:0",
    label: "F18:0 Fettsäure C18:0 (Stearinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F20:0",
    label: "F20:0 Fettsäure C20:0 (Arachinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F22:0",
    label: "F22:0 Fettsäure C22:0 (Behensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F24:0",
    label: "F24:0 Fettsäure C24:0 (Lignocerinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FAMS",
    label: "FAMS Fettsäure, einfach ungesättigt, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F14:1CN5",
    label: "F14:1CN5 Fettsäure C14:1 n-5 cis (Myristoleinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F16:1CN7",
    label: "F16:1CN7 Fettsäure C16:1 n-7 cis (Palmitoleinsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:1CN7",
    label: "F18:1CN7 Fettsäure C18:1 n-7 cis (Vaccensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:1CN9",
    label: "F18:1CN9 Fettsäure C18:1 n-9 cis (Ölsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F20:1CN9",
    label: "F20:1CN9 Fettsäure C20:1 n-9 cis (Gondosäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F22:1CN9",
    label: "F22:1CN9 Fettsäure C22:1 n-9 cis (Erucasäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FAPU",
    label: "FAPU Fettsäuren, mehrfach ungesättigt, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FAPUN3",
    label:
      "FAPUN3 Fettsäuren, mehrfach ungesättigt n-3 (Omega-3), gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:3CN3",
    label: "F18:3CN3 Fettsäure C18:3 n-3 all-cis (Alpha-Linolensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:4CN3",
    label: "F18:4CN3 Fettsäure C18:4 n-3 all-cis (Stearidonsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F20:5CN3",
    label: "F20:5CN3 Fettsäure C20:5 n-3 all-cis (Eicosapentaensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F22:5CN3",
    label: "F22:5CN3 Fettsäure C22:5 n-3 all-cis (Docosapentaensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F22:6CN3",
    label: "F22:6CN3 Fettsäure C22:6 n-3 all-cis (Docosahexaensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FAPUN6",
    label:
      "FAPUN6 Fettsäuren, mehrfach ungesättigt n-6 (Omega-6), gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:2CN6",
    label: "F18:2CN6 Fettsäure C18:2 n-6 cis, cis (Linolsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:2C9T11",
    label:
      "F18:2C9T11 Fettsäure C18:2 n-7 cis 9, trans 11 (konjugierte Linolsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F18:3CN6",
    label: "F18:3CN6 Fettsäure C18:3 n-6 all-cis (Gamma-Linolensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F20:2CN6",
    label: "F20:2CN6 Fettsäure C20:2 n-6 all-cis (Eicosadiensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F20:3CN6",
    label:
      "F20:3CN6 Fettsäure C20:3 n-6 all-cis (Dihomogamma-Linolensäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "F20:4CN6",
    label: "F20:4CN6 Fettsäure C20:4 n-6 all-cis (Arachidonsäure) [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "FAX",
    label: "FAX Fettsäuren, sonstige [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "CHORL",
    label: "CHORL Cholesterin [mg/100g]",
    unit: "mg",
    status: "out_of_scope",
  },
  {
    code: "AAE9",
    label: "AAE9 Aminosäuren, unentbehrlich, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "ALA",
    label: "ALA Alanin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "ARG",
    label: "ARG Arginin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "ASP",
    label: "ASP Asparaginsäure, inklusive Asparagin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "CYSTE",
    label: "CYSTE Cystein [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "GLU",
    label: "GLU Glutaminsäure, inklusive Glutamin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "GLY",
    label: "GLY Glycin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "HIS",
    label: "HIS Histidin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "ILE",
    label: "ILE Isoleucin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "LEU",
    label: "LEU Leucin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "LYS",
    label: "LYS Lysin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "MET",
    label: "MET Methionin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "PHE",
    label: "PHE Phenylalanin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "PRO",
    label: "PRO Prolin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "SER",
    label: "SER Serin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "THR",
    label: "THR Threonin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "TRP",
    label: "TRP Tryptophan [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "TYR",
    label: "TYR Tyrosin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "VAL",
    label: "VAL Valin [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
  {
    code: "NT",
    label: "NT Stickstoff, gesamt [g/100g]",
    unit: "g",
    status: "out_of_scope",
  },
] as const;
