// Generated by scripts/generate-watch-progress-x.mjs.
import SwiftUI

extension Path {
    /// Parses the absolute M/L/C/Z subset of SVG path data the brand geometry
    /// uses (see shared/src/brand/progressionX.geometry.json).
    init(svgPathData data: String) {
        self.init()
        var tokens: [String] = []
        var number = ""
        func flush() {
            if !number.isEmpty { tokens.append(number); number = "" }
        }
        for character in data {
            if character.isLetter {
                flush()
                tokens.append(String(character))
            } else if character == "-" {
                flush()
                number = "-"
            } else if character.isNumber || character == "." {
                number.append(character)
            } else {
                flush()
            }
        }
        flush()

        var index = 0
        func next() -> CGFloat {
            defer { index += 1 }
            return index < tokens.count ? CGFloat(Double(tokens[index]) ?? 0) : 0
        }
        while index < tokens.count {
            let command = tokens[index]
            index += 1
            switch command {
            case "M":
                move(to: CGPoint(x: next(), y: next()))
            case "L":
                addLine(to: CGPoint(x: next(), y: next()))
            case "C":
                let control1 = CGPoint(x: next(), y: next())
                let control2 = CGPoint(x: next(), y: next())
                addCurve(to: CGPoint(x: next(), y: next()), control1: control1, control2: control2)
            case "Z":
                closeSubpath()
            default:
                continue
            }
        }
    }
}

/// How much of each segment's guide is lit for `percent`: one scalar runs
/// through the segments in order, like `getProgressionXReveal` in shared.
func progressXRevealFractions(percent: Double?) -> [Double] {
    let segments = ProgressXGeometry.segments
    guard let percent else { return segments.map { _ in 0 } }
    let total = segments.reduce(0) { $0 + $1.length }
    var remaining = min(max(percent, 0), 100) / 100 * total
    return segments.map { segment in
        let visible = min(segment.length, max(0, remaining))
        remaining -= visible
        return segment.length > 0 ? visible / segment.length : 0
    }
}

/// One layer of the X: either the dim outline everything sits on, or the
/// lit part. Kept as two views so the lit layer alone can be marked
/// accentable when the face tints complications.
private struct ProgressXLayer: View {
    enum Kind { case baseline, lit }

    let kind: Kind
    let percent: Double?
    /// Multiplies the brand stroke width. Complications are drawn much
    /// smaller than the phone card, where a 7-unit stroke would vanish.
    let lineScale: CGFloat
    let fullColor: Bool

    var body: some View {
        Canvas { context, size in
            let side = min(size.width, size.height)
            let scale = side / ProgressXGeometry.size.width
            context.translateBy(
                x: (size.width - side) / 2,
                y: (size.height - side) / 2
            )
            context.scaleBy(x: scale, y: scale)

            let fractions = progressXRevealFractions(percent: percent)
            for (index, segment) in ProgressXGeometry.segments.enumerated() {
                let shading: GraphicsContext.Shading
                if kind == .baseline {
                    shading = .color(
                        fullColor ? ProgressXGeometry.baselineDark : Color.white.opacity(0.35)
                    )
                } else {
                    let fraction = fractions[index]
                    guard fraction > 0 else { continue }
                    shading = fullColor
                        ? .linearGradient(
                            Gradient(colors: [segment.from, segment.to]),
                            startPoint: segment.gradientStart,
                            endPoint: segment.gradientEnd
                        )
                        : .color(.white)
                    if fraction < 1 {
                        let reveal = Path(svgPathData: segment.guide)
                            .trimmedPath(from: 0, to: CGFloat(fraction))
                            .strokedPath(
                                StrokeStyle(
                                    lineWidth: segment.revealWidth * lineScale,
                                    lineCap: .round,
                                    lineJoin: .round
                                )
                            )
                        var clipped = context
                        clipped.clip(to: reveal)
                        draw(segment, in: clipped, with: shading)
                        continue
                    }
                }
                draw(segment, in: context, with: shading)
            }
        }
    }

    private func draw(
        _ segment: ProgressXSegment,
        in context: GraphicsContext,
        with shading: GraphicsContext.Shading
    ) {
        let path = Path(svgPathData: segment.path)
        if segment.isStroke {
            context.stroke(
                path,
                with: shading,
                style: StrokeStyle(
                    lineWidth: segment.strokeWidth * lineScale,
                    lineCap: segment.roundCap ? .round : .butt,
                    lineJoin: .round
                )
            )
            if let taper = segment.taperPath {
                context.fill(Path(svgPathData: taper), with: shading)
            }
        } else {
            // The sweep is a filled outline; a matching stroke thickens it
            // by the same amount the stroked segments grew.
            context.fill(path, with: shading)
            if lineScale > 1 {
                context.stroke(
                    path,
                    with: shading,
                    style: StrokeStyle(
                        lineWidth: 7 * (lineScale - 1),
                        lineJoin: .round
                    )
                )
            }
        }
    }
}

struct ProgressXDrawing: View {
    let percent: Double?
    var lineScale: CGFloat = 1.6
    var fullColor: Bool = true
    var body: some View {
        ZStack {
            ProgressXLayer(kind: .baseline, percent: nil, lineScale: lineScale, fullColor: fullColor)
            if let percent, percent > 0 {
                ProgressXLayer(kind: .lit, percent: percent, lineScale: lineScale, fullColor: fullColor)
            }
        }.opacity(percent == nil ? 0.62 : 1)
    }
}
