// Generated by ts-to-zod
import { z } from "zod";

export const mealPlansIdSchema = z.uuid();

const userIdSchema = z.uuid();

const mealsIdSchema = z.uuid();

const foodsIdSchema = z.uuid();

const foodVariantsIdSchema = z.uuid();

const mealTypesIdSchema = z.uuid();

export const mealPlansSchema = z.object({
  id: mealPlansIdSchema,
  user_id: userIdSchema,
  meal_id: mealsIdSchema.nullable(),
  food_id: foodsIdSchema.nullable(),
  variant_id: foodVariantsIdSchema.nullable(),
  quantity: z.number().nullable(),
  unit: z.string().nullable(),
  plan_date: z.date(),
  is_template: z.boolean().nullable(),
  template_name: z.string().nullable(),
  day_of_week: z.number().nullable(),
  created_at: z.date(),
  updated_at: z.date(),
  meal_type_id: mealTypesIdSchema,
  template_version_id: z.uuid().nullable(),
  assignment_id: z.uuid().nullable(),
  state: z.enum(["planned", "confirmed", "skipped", "cancelled"]),
  item_snapshot: z.json().nullable(),
});

export const mealPlansInitializerSchema = z.object({
  id: mealPlansIdSchema.optional(),
  user_id: userIdSchema,
  meal_id: mealsIdSchema.optional().nullable(),
  food_id: foodsIdSchema.optional().nullable(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional().nullable(),
  unit: z.string().optional().nullable(),
  plan_date: z.date(),
  is_template: z.boolean().optional().nullable(),
  template_name: z.string().optional().nullable(),
  day_of_week: z.number().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  meal_type_id: mealTypesIdSchema,
  template_version_id: z.uuid().nullable().optional(),
  assignment_id: z.uuid().nullable().optional(),
  state: z.enum(["planned", "confirmed", "skipped", "cancelled"]).optional(),
  item_snapshot: z.json().nullable().optional(),
});

export const mealPlansMutatorSchema = z.object({
  id: mealPlansIdSchema.optional(),
  user_id: userIdSchema.optional(),
  meal_id: mealsIdSchema.optional().nullable(),
  food_id: foodsIdSchema.optional().nullable(),
  variant_id: foodVariantsIdSchema.optional().nullable(),
  quantity: z.number().optional().nullable(),
  unit: z.string().optional().nullable(),
  plan_date: z.date().optional(),
  is_template: z.boolean().optional().nullable(),
  template_name: z.string().optional().nullable(),
  day_of_week: z.number().optional().nullable(),
  created_at: z.date().optional(),
  updated_at: z.date().optional(),
  meal_type_id: mealTypesIdSchema.optional(),
  template_version_id: z.uuid().nullable().optional(),
  assignment_id: z.uuid().nullable().optional(),
  state: z.enum(["planned", "confirmed", "skipped", "cancelled"]).optional(),
  item_snapshot: z.json().nullable().optional(),
});

export type MealPlans = z.infer<typeof mealPlansSchema>;
export type MealPlansInitializer = z.infer<typeof mealPlansInitializerSchema>;
export type MealPlansMutator = z.infer<typeof mealPlansMutatorSchema>;
