// Generated by scripts/generate-watch-progress-x.mjs from
// shared/src/brand/progressionX.geometry.json. Do not edit by hand; run
// `node scripts/generate-watch-progress-x.mjs` after changing the geometry.

import SwiftUI

struct ProgressXSegment {
    let id: String
    let isStroke: Bool
    let path: String
    let taperPath: String?
    let guide: String
    let strokeWidth: CGFloat
    let revealWidth: CGFloat
    let roundCap: Bool
    /// Length of `guide`, measured the same way as the shared reveal.
    let length: Double
    let gradientStart: CGPoint
    let gradientEnd: CGPoint
    let from: Color
    let to: Color
}

enum ProgressXGeometry {
    static let size = CGSize(width: 320, height: 320)
    static let baselineDark = Color(red: 0.322, green: 0.392, blue: 0.467)
    static let segments: [ProgressXSegment] = [
        ProgressXSegment(
            id: "lower-left",
            isStroke: true,
            path: "M159 113 L68 218 C55 233 61 253 82 254 L98 254 C106 254 111 252 117 245 L151 204",
            taperPath: nil,
            guide: "M151 204 L117 245 C111 252 106 254 98 254 L82 254 C61 253 55 233 68 218 L159 113",
            strokeWidth: 7,
            revealWidth: 14,
            roundCap: true,
            length: 280.19,
            gradientStart: CGPoint(x: 120, y: 235),
            gradientEnd: CGPoint(x: 159, y: 113),
            from: Color(red: 1, green: 0.071, blue: 0.235),
            to: Color(red: 1, green: 0.608, blue: 0.173)
        ),
        ProgressXSegment(
            id: "upper-left",
            isStroke: true,
            path: "M119 155 L68 96 C54 80 64 60 84 60 L98 60 C106 60 112 63 118 70 L159 113",
            taperPath: nil,
            guide: "M159 113 L118 70 C112 63 106 60 98 60 L84 60 C64 60 54 80 68 96 L119 155",
            strokeWidth: 7,
            revealWidth: 14,
            roundCap: false,
            length: 225.842,
            gradientStart: CGPoint(x: 165, y: 95),
            gradientEnd: CGPoint(x: 100, y: 150),
            from: Color(red: 1, green: 0.608, blue: 0.173),
            to: Color(red: 0.969, green: 0.933, blue: 0.212)
        ),
        ProgressXSegment(
            id: "upper-right",
            isStroke: true,
            path: "M159 113 L202 70 C208 63 214 60 222 60 L235 60 C255 60 264 80 250 97 L191 157",
            taperPath: "M188.5 154.5 L193.5 159.5 L174 178 Z",
            guide: "M159 113 L202 70 C208 63 214 60 222 60 L235 60 C255 60 264 80 250 97 L174 178",
            strokeWidth: 7,
            revealWidth: 14,
            roundCap: true,
            length: 259.863,
            gradientStart: CGPoint(x: 159, y: 90),
            gradientEnd: CGPoint(x: 235, y: 150),
            from: Color(red: 0.969, green: 0.933, blue: 0.212),
            to: Color(red: 0.698, green: 0.961, blue: 0.271)
        ),
        ProgressXSegment(
            id: "lower-right",
            isStroke: true,
            path: "M190.5 156.5 L250 223 C264 240 254 254 235 254 L220 254",
            taperPath: nil,
            guide: "M190.5 156.5 L250 223 C264 240 254 254 235 254 L220 254",
            strokeWidth: 7,
            revealWidth: 14,
            roundCap: false,
            length: 150.98,
            gradientStart: CGPoint(x: 190, y: 150),
            gradientEnd: CGPoint(x: 240, y: 250),
            from: Color(red: 0.698, green: 0.961, blue: 0.271),
            to: Color(red: 0.494, green: 0.961, blue: 0.361)
        ),
        ProgressXSegment(
            id: "sweep",
            isStroke: false,
            path: "M214 103 C180 121 145 144 132 158 C122 169 123 181 135 193 L199 249 C205 254 212 257.5 220 257.5 L220 250.5 C214 250.5 208 247 203 242 L148 183 C140 175 139 170 146 161 C159 146 190 120 214 103 Z",
            taperPath: nil,
            guide: "M220 254 C212 254 205 254 199 249 L135 193 C123 181 122 169 132 158 C145 144 180 121 214 103",
            strokeWidth: 0,
            revealWidth: 32,
            roundCap: true,
            length: 245.922,
            gradientStart: CGPoint(x: 220, y: 254),
            gradientEnd: CGPoint(x: 214, y: 103),
            from: Color(red: 0.494, green: 0.961, blue: 0.361),
            to: Color(red: 0.133, green: 0.976, blue: 0.471)
        ),
    ]
}
